"""'init3'

Revision ID: 36982af37e29
Revises: 4e92ee34854b
Create Date: 2017-12-20 22:59:06.030000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36982af37e29'
down_revision = '4e92ee34854b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.drop_constraint(u'article_ibfk_3', 'article', type_='foreignkey')
    op.drop_column(u'article', 'tag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'article', sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'article_ibfk_3', 'article', 'tag', ['tag_id'], ['id'])
    op.drop_table('articles_tags')
    # ### end Alembic commands ###
