"""'init1'

Revision ID: 5cc15e97ad5c
Revises: dd4d873464de
Create Date: 2018-01-04 23:12:43.680000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cc15e97ad5c'
down_revision = 'dd4d873464de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('img', sa.BLOB(), nullable=True))
    op.drop_column('article', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('img_url', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('article', 'img')
    # ### end Alembic commands ###
