"""'init2'

Revision ID: 9a3724cf9cc0
Revises: 5cc15e97ad5c
Create Date: 2018-01-04 23:16:22.160000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3724cf9cc0'
down_revision = '5cc15e97ad5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('photo', sa.String(length=100), nullable=True))
    op.drop_column('article', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('img', sa.BLOB(), nullable=True))
    op.drop_column('article', 'photo')
    # ### end Alembic commands ###
